#include <cassert>  // IWYU pragma: keep
#include <cctype>   // IWYU pragma: keep
#include <cerrno>   // IWYU pragma: keep
#include <cfloat>   // IWYU pragma: keep
#include <climits>  // IWYU pragma: keep
#include <clocale>  // IWYU pragma: keep
#include <cmath>    // IWYU pragma: keep
#include <csetjmp>  // IWYU pragma: keep
#include <csignal>  // IWYU pragma: keep
#include <cstdarg>  // IWYU pragma: keep
#include <cstddef>  // IWYU pragma: keep
#include <cstdio>   // IWYU pragma: keep
#include <cstdlib>  // IWYU pragma: keep
#include <cstring>  // IWYU pragma: keep
#include <ctime>    // IWYU pragma: keep
#include <unistd.h> // IWYU pragma: keep

#include <cfenv>     // IWYU pragma: keep
#include <cinttypes> // IWYU pragma: keep
#include <cstdint>   // IWYU pragma: keep
#include <cwchar>    // IWYU pragma: keep
#include <cwctype>   // IWYU pragma: keep

#include <algorithm>          // IWYU pragma: keep
#include <array>              // IWYU pragma: keep
#include <atomic>             // IWYU pragma: keep
#include <bitset>             // IWYU pragma: keep
#include <chrono>             // IWYU pragma: keep
#include <complex>            // IWYU pragma: keep
#include <condition_variable> // IWYU pragma: keep
#include <deque>              // IWYU pragma: keep
#include <exception>          // IWYU pragma: keep
#include <forward_list>       // IWYU pragma: keep
#include <fstream>            // IWYU pragma: keep
#include <functional>         // IWYU pragma: keep
#include <future>             // IWYU pragma: keep
#include <initializer_list>   // IWYU pragma: keep
#include <iomanip>            // IWYU pragma: keep
#include <ios>                // IWYU pragma: keep
#include <iosfwd>             // IWYU pragma: keep
#include <iostream>           // IWYU pragma: keep
#include <istream>            // IWYU pragma: keep
#include <iterator>           // IWYU pragma: keep
#include <limits>             // IWYU pragma: keep
#include <list>               // IWYU pragma: keep
#include <locale>             // IWYU pragma: keep
#include <map>                // IWYU pragma: keep
#include <memory>             // IWYU pragma: keep
#include <mutex>              // IWYU pragma: keep
#include <new>                // IWYU pragma: keep
#include <numeric>            // IWYU pragma: keep
#include <ostream>            // IWYU pragma: keep
#include <queue>              // IWYU pragma: keep
#include <random>             // IWYU pragma: keep
#include <ratio>              // IWYU pragma: keep
#include <regex>              // IWYU pragma: keep
#include <scoped_allocator>   // IWYU pragma: keep
#include <set>                // IWYU pragma: keep
#include <sstream>            // IWYU pragma: keep
#include <stack>              // IWYU pragma: keep
#include <stdexcept>          // IWYU pragma: keep
#include <streambuf>          // IWYU pragma: keep
#include <string>             // IWYU pragma: keep
#include <system_error>       // IWYU pragma: keep
#include <thread>             // IWYU pragma: keep
#include <tuple>              // IWYU pragma: keep
#include <type_traits>        // IWYU pragma: keep
#include <typeindex>          // IWYU pragma: keep
#include <typeinfo>           // IWYU pragma: keep
#include <unordered_map>      // IWYU pragma: keep
#include <unordered_set>      // IWYU pragma: keep
#include <utility>            // IWYU pragma: keep
#include <valarray>           // IWYU pragma: keep
#include <vector>             // IWYU pragma: keep

#include <sys/resource.h>
#define STACK_SIZE_256M 268435456
